### ISSUE TITLE
Incorrect Spelling.

### ISSUE THREAD

**Issue by cloudrack-ca** [webvirtcloud/webvirtbackend#3]
![image](https://github.com/webvirtcloud/webvirtbackend/assets/145787423/4d6b4e85-69fe-46b2-ba6b-13c541a61c4f)

**Comment by cloudrack-ca** [comment]
mind you i know alot of works still being done on your guys end to release this amazing piece of software to the world BUT id like to point out that i have had much trouble installing and setting up even noting that this is still highly in development. Ansbile dosnt work do to "- lines" in file....long story short if you guys be kind enough to maybe get me a working instance or send me the proper setup steps and OS to use, as i am utilizing almalinux8 for this test and check but if i could be up and somewhat running using webvirt.cloud then i probably could contribute more to miss-spellings corrections ideas and more.

**Comment by retspen** [comment]
> mind you i know alot of works still being done on your guys end to release this amazing piece of software to the world BUT id like to point out that i have had much trouble installing and setting up even noting that this is still highly in development. Ansbile dosnt work do to "- lines" in file....long story short if you guys be kind enough to maybe get me a working instance or send me the proper setup steps and OS to use, as i am utilizing almalinux8 for this test and check but if i could be up and somewhat running using webvirt.cloud then i probably could contribute more to miss-spellings corrections ideas and more.

Helo, this repo https://github.com/webvirtcloud/webvirtcompute

**Comment by cloudrack-ca** [comment]
> > mind you i know alot of works still being done on your guys end to release this amazing piece of software to the world BUT id like to point out that i have had much trouble installing and setting up even noting that this is still highly in development. Ansbile dosnt work do to "- lines" in file....long story short if you guys be kind enough to maybe get me a working instance or send me the proper setup steps and OS to use, as i am utilizing almalinux8 for this test and check but if i could be up and somewhat running using webvirt.cloud then i probably could contribute more to miss-spellings corrections ideas and more.
> 
> Hello, check this repo https://github.com/webvirtcloud/webvirtcompute

Still choppy on full end user documentation try more of a virtfusion approach for enduser installs and documentation. https://virtfusion.com/

**Comment by cloudrack-ca** [comment]
To me the backend has compute no? this is where im confused + lacking of detailed documentation i.e setting up `br-int` and there seems to be errors as stated with the ansible file do to comments with a `-` starting line

**Comment by cloudrack-ca** [comment]
also please note i have many physical bare metal servers id like to switch off of https://convoypanel.com to make use of webvirtcloud instead.

**Comment by cloudrack-ca** [comment]
Thank you for applying touch-ups to documentation and more, @retspen lastly in regards to `br-int` and `br-ext` for better documentation you should state that there should be two networking interfaces for the two individual bridges

**Comment by retspen** [comment]
Thanks you. But it doesn't matter you can use the same interface for both bridges it only depends on your network topology.
